# Tebex v${version} - https://tebex.io
# Check out https://tebex.io/docs if you need help.

# Buy Command
# This is the command that players will use to open the Tebex GUI.
buy-command:
  enabled: true
  name: buy

# Whether to check for updates or not.
check-for-updates: true

# Automatic reporting of exceptions to Tebex
auto-report-enabled: true

# Debug Mode
verbose: false

# GUI Settings
gui:
  menu:
    home:
      title: "Server Shop"
      rows: 3
    category:
      title: "Viewing %category%"
      rows: 3
    sub-category:
      title: "Viewing %sub_category% (%category%)"
      rows: 1
  item:
    back:
      name: "&cBack"
      material: COMPASS
      lore: []
    category:
      name: "&b%category%"
      material: CHEST
      lore:
        - "&7Click to view packages!"
    package-sale:
      name: "&b%package_name%"
      material: PAPER
      lore:
        - "&7Price: &f%package_currency%%package_sale_price% &7(&m%package_currency%%package_price%&r&7)"
        - "&7"
        - "&7Click to purchase!"
    package:
      name: "&b%package_name%"
      material: PAPER
      lore:
        - "&7Price: &f%package_currency%%package_price%"
        - "&7"
        - "&7Click to purchase!"

# These settings are exclusive to this server.
# Do not share these credentials with anyone.
server:
  # Proxy Mode
  # If you are using BungeeCord/Velocity, set this to true.
  proxy: false

  # Secret Key
  # This is used to identify your server.
  secret-key: ''

# Configuration Version
# !! Do not change this value !!
config-version: 2