name: BuycraftX
main: net.buycraft.plugin.bukkit.BuycraftPlugin
version: ${pluginVersion}
author: Buycraft
commands:
  tebex:
    aliases: [buycraft]
    description: Main command for the Tebex plugin.