name: BuycraftX
main: net.buycraft.plugin.bukkit.BuycraftPlugin
version: ${pluginVersion}
author: Buycraft
api-version: "1.13"
commands:
  tebex:
    aliases: [buycraft]
    description: Main command for the Tebex plugin.